# Generated by Django 3.2.3 on 2021-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='checkbox',
            field=models.BooleanField(default=True),
        ),
    ]
