# Generated by Django 3.2.3 on 2021-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='checkbox',
        ),
        migrations.AddField(
            model_name='topic',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
